services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception
    restart: unless-stopped

  redis:
    image: redis
    build: ./requirements/bonus/redis
    container_name: redis
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  ftp:
    image: ftp
    build: ./requirements/bonus/ftp
    container_name: ftp
    depends_on:
      - wordpress
    ports:
      - "${FTP_PORT}:21"
      - "${FTP_PASV_MIN}-${FTP_PASV_MAX}:${FTP_PASV_MIN}-${FTP_PASV_MAX}"
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    secrets:
      - ftp_password
    networks:
      - inception
    restart: unless-stopped

  flask:
    image: flask
    build: ./requirements/bonus/flask
    container_name: flask
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  adminer:
    image: adminer
    build: ./requirements/bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  netdata:
    image: netdata
    build: ./requirements/bonus/netdata
    container_name: netdata
    ports:
      - "${NETDATA_PORT}:${NETDATA_PORT}"
    env_file:
      - .env
    environment:
      - DO_NOT_TRACK=1
    networks:
      - inception
    restart: unless-stopped

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ngusev/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ngusev/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
